- name: PLAY1
  hosts: local  # Corrected from 'host' to 'hosts'
  connection: local
  tasks:
    - name: play1 and task1
      ansible.builtin.debug:
        msg: "Hello from play1 and task1"

- name: PLAY2 and task1
  hosts: local  # Corrected from 'host' to 'hosts'
  connection: local
  tasks:
    - name: play2 and task1
      ansible.builtin.debug:
        msg: "Hello from play2 and task1"
