- name: variables
  hosts: web
  connection: local
  vars:
   COURSE: devops
   DURATION: "120 hrs"
   TRAINER: "sathish reddy"
  tasks:
  - name: print the variables
    vars:
    COURSE: Ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }} ,duration is  {{ DURATION }} , trainer is  {{ TRAINER }}"
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }} ,duration is  {{ DURATION }} , trainer is  {{ TRAINER }}"    